[package]
name = "urcl-llvm-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
dashu = { version = "0.4.2", default-features = false }
inkwell = { path = "../inkwell", features = ["llvm17-0-prefer-dynamic"] }
urcl-ast = { path = "../urcl-ast" }
